<script>
  window.VelaroConfig = {
    mainApi: '<?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/apimainurl')) ?>',
    cdn: '<?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/cdnurl')) ?>/',
    siteId: <?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/identifier')) ?>,
    groupId: <?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/group')) ?>,
  }
</script>

<script src="<?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/cdnurl')) ?>Scripts/launch.js"></script>
