<script>
  window.VelaroConfig = {
    mainApi: '<?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/apimainurl')) ?>',
    cdn: '<?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/cdnurl')) ?>/',
    siteId: <?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/identifier')) ?>,
    groupId: <?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/group')) ?>,
  }

  window.VelaroDataHelper = {
  data: JSON.parse(localStorage.getItem('mage-cache-storage')),

  getCustomerId: function(){
    if(this.data && this.data.customer && this.customer.data.websiteId){
      return this.data.websiteId;
    }
    return null;
  },

  getSubtotal: function(){
    if(this.data && this.data.cart && this.data.cart.subtotalAmount){
      return this.data.cart.this.data.cart.subtotalAmount;
    }
    return null;
  },

  getCartItems: function(){
    if(this.data && this.data.cart && this.data.cart.items && this.data.cart.items.length){
      return this.data.cart.items.map(function(cartItem){
        return {
          name: cartItem.product_name,
          price: cartItem.product_price_value,
          quantity: cartItem.qty,
          thumbnail: cartItem.product_image.src,
          url: carItem.product_url
        }
      })
    }

    return []
  },

  
  getRecentlyViewedItems: function(){
    if(this.data && this.data.recently_viewed_product && this.data.recently_viewed_product.items.length){
      return this.data.recently_viewed_product.items.map(function(cartItem){
        return {
          name: cartItem.product_name,
          thumbnail: cartItem.product_image.src,
          url: carItem.product_url
        }
      })
    }

    return []
  }
}
</script>

<script src="<?php echo ($this->helper('Velaro\Chat\helper\data')->getConfig('velaro/site/cdnurl')) ?>/scripts/launch.js"></script>
<script>
if(VelaroDataHelper.getCustomerId()){
  Velaro('linkToEcommerceId', {
    id: VelaroDataHelper.getCustomerId(),
    url: '<?php echo ($this->helper('Velaro\Chat\helper\data')->getCustomerUrlBase($this->helper('Magento\Backend\Helper\Data'))) ?>?customerid=' + VelaroDataHelper.getCustomerId() 
  });
}
</script>

<?php if ($this->helper('Velaro\Chat\helper\data')->isCheckoutSuccessPage()) {
	?>
<script>
  Velaro('recordEcommerceSale', 
    id: <?php echo ($this->helper('Velaro\Chat\helper\data')->getOrderId()) ?>,
    url: '<?php echo ($this->helper('Velaro\Chat\helper\data')->getOrderUrl()) ?>'
  );
</script>
<?php
}
else {
?>
<script>
  Velaro('postEcommerceData',
  {
    cartTotal: VelaroDataHelper.getSubtotal(),
    cartItems: VelaroDataHelper.getCartItems(),
    recentlyViewed: VelaroDataHelper.getRecentlyViewedItems()
  });
</script>
<?php
}
?>
